# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('BUS', 'Business'), ('NET', 'Network'), ('SOC', 'Social'), ('FAM', 'Family')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_death', models.DateTimeField()),
                ('person_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'unknown')], default='U', max_length=1)),
                ('person_type', models.CharField(choices=[('SUS', 'Suspect'), ('WIT', 'Witness'), ('INF', 'Informant'), ('INT', 'Intel')], max_length=3)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cda.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cda.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cda.Person')),
            ],
        ),
    ]
